### ISSUE TITLE
cURL error 60: SSL certificate problem:

### ISSUE THREAD

**Issue by saeedmpt** [dasun4u/laravel-shoutout-messaging#2]
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
http://127.0.0.1:8000/admin/product

**Comment by dasun4u** [comment]
> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
> http://127.0.0.1:8000/admin/product

@saeedmpt
This is not a package issue. This cURL issue is on your local server

Let’s follow these simple steps:

Download this bundle of root certificates: https://curl.haxx.se/ca/cacert.pem
Put in any location of your server.
Open php.ini and add this line: curl.cainfo = "[the_location]\cacert.pem"
Restart your webserver.
 That’s it. 🙂
