### ISSUE TITLE
Laravel with shoutout

### ISSUE THREAD

**Issue by matheeshasarith** [dasun4u/laravel-shoutout-messaging#3]
"res": {
            "message": "Authentication Failure!"
        }

................????????

**Comment by dasun4u** [comment]
@matheeshasarith Did you set the api_key in `config/shoutout_message.php` file?
You can take it from ShoutOut Dashboard.

**Comment by matheeshasarith** [comment]
Done.  It's working now.

**Comment by dasun4u** [comment]
Thanks for your reply.
